name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest





    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: autest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
      
      
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.14'
          extensions: mbstring, intl, bcmath, pdo, mysqli

      - name: Install Composer dependencies
        run: composer install --no-interaction






      - name: Run migrations
        run: php spark migrate --env testing

      - name: Give execution permission to PHPUnit
        run: chmod +x ./vendor/bin/phpunit






      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text
